#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Emulates storage service availabilities with launch/shutdown control over local file servers, containers, proxies
# Syntax: mcemu-server <inifile> [<hook>] [<model>]
# - model==stable: emulate 100% availability (= reliability)
# - with csvoutput==True: Variant of mcemu-server which only logs to CSV without launch/shutdown
# Attention: Value per service is unavailability

import sys
import time
import random
import subprocess
import os

import dockerhook

csvoutput = False

sys.path.append("..")
sys.path.append(".")
#os.chdir(os.path.dirname(sys.argv[0]))

from mcsalgorithms.distavail import Service, ServiceSet
from mcsalgorithms.servicegen import ServiceGenerator

class EmulatedService:
	def __init__(self, service, hook, ftpport=None, httpport=None, proxyport=None, dockerimage=None, output=True):
		self.service = service
		self.hook = hook
		self.ftpport = ftpport
		self.httpport = httpport
		self.proxyport = proxyport
		self.dockerimage = dockerimage
		self.avonline = 1
		self.avoffline = 0
		self.process = None
		self.online = None
		self.output = output
		self.prepareservice()
		self.startservice()

	def realav(self):
		realav = float(self.avonline) / (self.avonline + self.avoffline)
		return realav

	def __repr__(self):
		global csvoutput

		if csvoutput:
			unavailablestate = "10"[self.online]
			return unavailablestate
		else:
			properties = ""
			if "pop" in self.service.properties:
				properties += ",load=%3.4f" % 0.0
			onlinestate = " x"[self.online]
			if self.hook == "gatling":
				return "ES[%s:ftp:%i,http:%i,av=%3.4f,realav:%3.4f%s][%s]" % (self.service.name, self.ftpport, self.httpport, self.service.availability, self.realav(), properties, onlinestate)
			elif self.hook == "morebalance":
				return "ES[%s:proxy:%i,av=%3.4f,realav:%3.4f%s][%s]" % (self.service.name, self.proxyport, self.service.availability, self.realav(), properties, onlinestate)
			else:
				return "ES[%s:av=%3.4f,realav:%3.4f%s][%s]" % (self.service.name, self.service.availability, self.realav(), properties, onlinestate)

	def prepareservice(self):
		if self.hook == "gatling":
			self.workdir = os.path.join(os.getcwd(), "_rootdirs", service.name)
			try:
				os.makedirs(self.workdir)
			except OSError:
				pass

	def startservice(self):
		if self.hook == "gatling":
			origdir = os.getcwd()
			cmd = "gatling -n -S -p %i -fp %i" % (self.httpport, self.ftpport)
			os.chdir(self.workdir)
			self.process = subprocess.Popen(cmd.split(" "))
			os.chdir(origdir)
			if self.output:
				print ">> %s -> %i" % (cmd, self.process.pid)

			if "pop" in self.service.properties:
				# tsung -f tsung_http_simple.xml start
				pass
		elif self.hook == "morebalance":
			config = "%i use localhost as 80" % self.proxyport
			cmd = "morebalance -i '%s'" % config
			self.process = subprocess.Popen(["morebalance", "-i", config])
			if self.output:
				print ">> %s -> %i" % (cmd, self.process.pid)
		elif self.hook == "docker":
			if self.dockerimage:
				if self.output:
					print ">> run docker image", self.dockerimage
				dockerhook.instantiate(self.dockerimage, output=self.output)
			else:
				if self.output:
					print ">> cannot run non-existing docker image"
		self.online = True

	def stopservice(self):
		if self.hook == "gatling":
			if self.output:
				print ">> kill %i" % self.process.pid
			self.process.kill()
			self.process = None
		elif self.hook == "morebalance":
			if self.output:
				print ">> kill %i and sub-thread" % self.process.pid
			try:
				pidstring = subprocess.check_output(["pidof", "morebalance"])
				pids = pidstring.strip().split()
				for pid in pids:
					if int(pid) == self.process.pid + 1:
						os.system("kill %s" % pid)
			except:
				pass
			self.process.kill()
			self.process = None
		elif self.hook == "docker":
			if self.dockerimage:
				if self.output:
					print ">> kill docker image", self.dockerimage
				dockerhook.shutdown(self.dockerimage, output=self.output)
			else:
				if self.output:
					print ">> cannot kill non-existing docker image"
		self.online = False

if len(sys.argv) != 2 and (len(sys.argv) != 3 or sys.argv[2] not in ("noop", "gatling", "docker", "morebalance")) and (len(sys.argv) != 4 or sys.argv[3] not in ("convergence", "incident", "stable")):
	print "Syntax: mcemu-server <inifile> [<hook>] [<model>]"
	print "Hooks: noop(default),gatling,docker,morebalance"
	print "Models: convergence(default),incident,stable"
	print "Semantics of stable: availability = 100%"
	sys.exit(1)

hook = "noop"
if len(sys.argv) >= 3:
	hook = sys.argv[2]

model = "convergence"
if len(sys.argv) >= 4:
	model = sys.argv[3]

sg = ServiceGenerator()
services = sg.loadservices(sys.argv[1])

if not csvoutput:
	print "Services to emulate:"
	print services
	print "Execution hook:", hook
	print "Unavailability:", model

dockerimages = []
if hook == "docker":
	dockerimages = dockerhook.get_docker_images()
	if not csvoutput:
		print "Docker images:", dockerimages
	if len(services) != len(dockerimages):
		print "WARNING: unequal service/docker image count; may use default availabilities"

ftpport = None
httpport = None
proxyport = None
if hook == "gatling":
	ftpport = 2000
	httpport = 3000
elif hook == "morebalance":
	proxyport = 8080

emulatedservices = []
for service in services:
	dockerimage = None
	if hook == "docker":
		try:
			index = dockerimages.index(service.name)
			dockerimage = dockerimages.pop(index)
		except:
			print "WARNING: docker image %s not found on the host" % service.name
	emulatedservices.append(EmulatedService(service, hook, ftpport, httpport, proxyport, dockerimage, output=not csvoutput))
	if hook == "gatling":
		ftpport += 1
		httpport += 1
	elif hook == "morebalance":
		proxyport += 1
if hook == "docker" and len(dockerimages) > 0:
	print "WARNING: unconfigured docker images %s" % str(dockerimages)

if csvoutput:
	print "#time,onlinestate(s)..."
else:
	print "Emulated services:"
	print emulatedservices

	print "Emulation starts..."
inittime = int(time.time())
incidenttime = None
while True:
	time.sleep((1, 5)[model == "stable"])

	for es in emulatedservices:
		if model == "stable":
			continue

		if es.online:
			es.avonline += 1
		else:
			es.avoffline += 1

		avdiff = es.realav() - es.service.availability
		switchprobability = random.random()

		if model == "convergence":
			if es.online and avdiff > 0 and abs(avdiff) > switchprobability:
				es.stopservice()
			elif not es.online and avdiff < 0 and abs(avdiff) > switchprobability:
				es.startservice()
		elif model == "incident":
			if es.online and switchprobability > es.service.availability and avdiff > 0.0:
				es.stopservice()
				incidenttime = time.time()
			elif not es.online and incidenttime and time.time() - incidenttime > 50 + random.random() * 50 + (1.0 - es.service.availability) * 1000:
				es.startservice()
				incidenttime = None

	if csvoutput:
		print "%i,%s" % (int(time.time()) - inittime, ",".join([str(x) for x in emulatedservices]))
	else:
		print "* virtual time [%5i]: %s" % (int(time.time()) - inittime, emulatedservices)
