#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Emulates storage service availabilities with launch/shutdown control over local FTP/HTTP servers (gatling)
# Syntax: mcsemu-server <inifile> [stable]
# - stable: emulate 100% availability (= reliability)

import sys
import time
import random
import subprocess
import os

sys.path.append("..")
from mcsalgorithms.distavail import Service, ServiceSet
from mcsalgorithms.servicegen import ServiceGenerator

class EmulatedService:
	def __init__(self, service, ftpport, httpport):
		self.service = service
		self.ftpport = ftpport
		self.httpport = httpport
		self.avonline = 1
		self.avoffline = 0
		self.process = None
		self.online = None
		self.workdir = os.path.join(os.getcwd(), "_rootdirs", service.name)
		try:
			os.makedirs(self.workdir)
		except OSError:
			pass
		self.startservice()

	def realav(self):
		realav = float(self.avonline) / (self.avonline + self.avoffline)
		return realav

	def __repr__(self):
		onlinestate = " x"[self.online]
		return "ES[%s:ftp:%i,http:%i,av=%3.4f,realav:%3.4f][%s]" % (self.service.name, self.ftpport, self.httpport, self.service.availability, self.realav(), onlinestate)

	def startservice(self):
		origdir = os.getcwd()
		cmd = "gatling -n -S -p %i -fp %i" % (self.httpport, self.ftpport)
		os.chdir(self.workdir)
		self.process = subprocess.Popen(cmd.split(" "))
		os.chdir(origdir)
		print ">> %s -> %i" % (cmd, self.process.pid)
		self.online = True

	def stopservice(self):
		print ">> kill %i" % self.process.pid
		self.process.kill()
		self.process = None
		self.online = False

if len(sys.argv) != 2 and (len(sys.argv) != 3 or sys.argv[2] != "stable"):
	print "Syntax: mcsemu-server <inifile> [stable]"
	sys.exit(1)

stable = False
if len(sys.argv) == 3 and sys.argv[2] == "stable":
	stable = True

sg = ServiceGenerator()
services = sg.loadservices(sys.argv[1])

print "Services to emulate:"
print services

ftpport = 2000
httpport = 3000
emulatedservices = []
for service in services:
	emulatedservices.append(EmulatedService(service, ftpport, httpport))
	ftpport += 1
	httpport += 1

print "Emulated services:"
print emulatedservices

print "Emulation starts..."
inittime = int(time.time())
while True:
	time.sleep((1, 5)[stable])

	for es in emulatedservices:
		if stable:
			continue

		if es.online:
			es.avonline += 1
		else:
			es.avoffline += 1

		avdiff = es.realav() - es.service.availability
		switchprobability = random.random()

		if es.online:
			if avdiff > 0 and abs(avdiff) > switchprobability:
				es.stopservice()
		elif not es.online:
			if avdiff < 0 and abs(avdiff) > switchprobability:
				es.startservice()

	print "* virtual time [%5i]: %s" % (int(time.time()) - inittime, emulatedservices)
